---
- name: Install fail2ban (RedHat).
  dnf:
    name: fail2ban
    state: present
    enablerepo: epel
  when: ansible_os_family == 'RedHat'

- name: Install fail2ban (Debian).
  apt:
    name: fail2ban
    state: present
  when: ansible_os_family == 'Debian'

- name: Copy jail custom configuration file into place.
  template:
    src: "templates/{{ security_fail2ban_custom_configuration_template }}"
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: 0644
  register: fail2ban_config

- name: Copy fail2ban custom configuration file into place.
  template:
    src: templates/fail2ban.local.j2
    dest: /etc/fail2ban/fail2ban.local
    owner: root
    group: root
    mode: 0644
  when:
    - ansible_os_family == 'Debian'
    - ansible_distribution_major_version | int >= 12
  register: fail2ban_config

- name: reload fail2ban
  service:
    name: fail2ban
    state: reloaded
  when: fail2ban_config.changed

- name: Ensure fail2ban is running and enabled on boot.
  service:
    name: fail2ban
    state: started
    enabled: true