---
- name: Set the ssh_config_file variable.
  set_fact:
    ssh_config_file: "{{ ssh.ssh_configuration.ssh_config_file }}"
  when: ssh_config_file is not defined

- name: Set the Port variable.
  set_fact:
    ssh_port: "{{ ssh.ssh_configuration.ssh_port }}"
  when: ssh_port is not defined

- name: Set the MaxAuthTries variable.
  set_fact:
    MaxAuthTries: "{{ ssh.ssh_configuration.MaxAuthTries }}"
  when: AuthTries is not defined

- name: Set the MaxAuthTries variable.
  set_fact:
    MaxSessions: "{{ ssh.ssh_configuration.MaxSessions }}"
  when: MaxSessions is not defined

- name: Set the AllowedUsers variable.
  set_fact:
    AllowedUsers: "{{ ssh.ssh_configuration.AllowedUsers }}"
  when: AllowedUsers is not defined

- name: Populate service facts.
  service_facts:

- name: Ensure OpenSSH is installed (ON DEBIAN LIKE DISTROs)
  apt:
    name: openssh-server
    state: present
    update_cache: true
  when: ansible_os_family == 'Debian'

- name: Ensure OpenSSH is installed (ON REDHAT LIKE DISTROs)
  dnf:
    name: openssh-server
    state: present
  when: ansible_os_family == 'RedHat'

- name: Ensure OpenSSH is running
  service:
    name: sshd
    state: started
    enabled: true

- name: Generate ssh configuration file.
  template:
    src: templates/sshd.conf.j2
    dest: "{{ ssh.ssh_configuration.ssh_config_file }}"
    mode: 0750
  register: sshd_config
  when: ssh.ssh_configuration.ssh_ansible_managed | bool

- name: restart sshd
  service:
    name: sshd
    state: restarted
  when: sshd_config.changed