# Include the OS specific variables
- name: Include specific OS variables
  include_vars: "vars/{{ ansible_os_family }}.yml"

- name: Import update debian playbook
  import_tasks: update-debian.yml
  when: ansible_os_family == 'Debian'

- name: Import update redhat playbook
  import_tasks: update-redhat.yml
  when: ansible_os_family == 'RedHat'

